---
- name: Install MacOS Software 
  hosts: localhost 
  become: false 
  
  vars:
    brew_cask_taps:
      - homebrew/cask-fonts
    brew_cask_packages:
      - firefox
      - obsidian
      - visual-studio-code
      - raycast
      - bitwarden
      - messenger
      - spotify
      - slack
      - mongodb-compass-isolated-edition
      - todoist
      - mqtt-explorer
      - microsoft-remote-desktop
      - font-fira-code
    install_homebrew_if_missing: false
    upgrade_homebrew_packages: false

  pre_tasks:
    - name: Ensuring Homebrew Is Installed
      stat:
        path: /usr/local/bin/brew
      register: homebrew_check

    - name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
      fail:
        msg: Homebrew is missing...Install from http://brew.sh/
      when:
        - not homebrew_check.stat.exists
        - not install_homebrew_if_missing

    - name: Installing Homebrew
      shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      when:
        - not homebrew_check.stat.exists
        - install_homebrew_if_missing

  tasks:
    - name: Updating Homebrew
      homebrew:
        update_homebrew: true
      when: homebrew_check.stat.exists

    - name: Upgrading Homebrew Packages
      homebrew:
        upgrade_all: "{{ upgrade_homebrew_packages }}"
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Installing Homebrew Cask Taps
      homebrew_tap:
        name: "{{ brew_cask_taps }}"
        state: present
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

    - name: Installing Homebrew Cask Packages
      homebrew_cask:
        name: "{{ brew_cask_packages }}"
        state: present
      register: result
      until: result is successful
      when: homebrew_check.stat.exists

#    - name: Installing Homebrew Packages
#      homebrew:
#        name: "{{ brew_packages }}"
#        state: present
#      register: result
#      until: result is successful
#      when: homebrew_check.stat.exists

# source - https://gist.githubusercontent.com/mrlesmithjr/f3c15fdd53020a71f55c2032b8be2eda/raw/be44272ce751e7bba41b6c7c5058a463a8f88463/ansible-macos-homebrew-packages.yml
# https://opensource.com/article/22/6/install-software-macos-ansible-homebrew
